import { useNavigate } from 'react-router-dom';
import { ArrowRight, Sparkles, CheckCircle, PenTool } from 'lucide-react';
import './landingPage.css';

const LandingPage = () => {
    const navigate = useNavigate();

    return (
        <div className="landing-page">
            <div className="orb orb-1"></div>
            <div className="orb orb-2"></div>
            
            <nav className="landing-nav glass-card">
                <div className="nav-logo">LinkedIn<span className="text-glow">Gen</span></div>
                <div className="nav-links">
                    <button onClick={() => navigate('/generate')} className="btn btn-outline">Generator</button>
                    <button onClick={() => navigate('/dashboard')} className="btn btn-primary">Dashboard</button>
                </div>
            </nav>

            <section className="hero-section">
                <div className="hero-content animate-fade-in-up">
                    <div className="badge">
                        <Sparkles size={16} />
                        <span>AI-Powered Professional Branding</span>
                    </div>
                    <h1 className="hero-title">
                        Craft the Perfect <br />
                        <span className="gradient-text">LinkedIn Presence</span>
                    </h1>
                    <p className="hero-subtitle">
                        Stand out to recruiters and clients with professional, tailored content generated by advanced AI. 
                        Optimize your tone, focus, and impact in seconds.
                    </p>
                    <div className="hero-actions">
                        <button onClick={() => navigate('/generate')} className="btn btn-primary btn-lg">
                            Get Started Free <ArrowRight size={20} />
                        </button>
                    </div>
                </div>
            </section>

            <section className="features-section">
                <div className="feature-card glass-card-hover">
                    <div className="feature-icon"><PenTool size={32} /></div>
                    <h3>Instant Generation</h3>
                    <p>Create professional descriptions based on your rough notes instantly.</p>
                </div>
                <div className="feature-card glass-card-hover">
                    <div className="feature-icon"><Sparkles size={32} /></div>
                    <h3>Tone Adjustment</h3>
                    <p>Switch between Professional, Casual, Confident, and more with one click.</p>
                </div>
                <div className="feature-card glass-card-hover">
                    <div className="feature-icon"><CheckCircle size={32} /></div>
                    <h3>Optimization</h3>
                    <p>Automatically include keywords that recruiters are looking for.</p>
                </div>
            </section>
        </div>
    );
};

export default LandingPage;
